#!/usr/bin/python3
import argparse

from devtools import pprint

from stembot.executor.agent import ControlFormClient
from stembot.dao import kvstore
from stembot.types.control import DeletePeers, DiscoverPeer, GetPeers, GetRoutes

parser = argparse.ArgumentParser(description='peer command line interface')

subparsers = parser.add_subparsers(help='commands')

set_parser = subparsers.add_parser('set', help='set peer')

set_parser.add_argument(
    '--ttl',
    dest='ttl',
    action='store',
    help='time-to-live (seconds)',
    type=int
)
set_parser.add_argument(
    '-p',
    dest='polling',
    action='store_true',
    help='enable polling'
)
set_parser.add_argument('peer_url', action='store', help='url')

del_parser = subparsers.add_parser('del', help='delete peer')
del_parser.add_argument('--all', dest='del_all_agents', action='store_true')
del_parser.add_argument('--agtuuid', dest='del_agtuuid', action='store')

list_parser = subparsers.add_parser('list')
list_parser.add_argument(
    '-p',
    dest='list_peers',
    action='store_true',
    help='list peers'
)
list_parser.add_argument(
    '-r',
    dest='list_routes',
    action='store_true',
    help='list routes'
)

kargs = vars(parser.parse_args())

client = ControlFormClient(url='http://127.0.0.1:8080/control', secret_digest=kvstore.get('secret_digest'))

if 'peer_url' in kargs:
    pprint(client.send_control_form(DiscoverPeer(
        url=kargs['peer_url'],
        polling=kargs['polling'],
        ttl=kargs['ttl'],
    )))

if 'del_all_agents' in kargs:
    pprint(client.send_control_form(DeletePeers()))

if 'del_agtuuid' in kargs:
    pprint(client.send_control_form(DeletePeers(agtuuids=[kargs['del_agtuuid']])))

if 'list_peers' in kargs:
    pprint(client.send_control_form(GetPeers()))

if 'list_routes' in kargs:
    pprint(client.send_control_form(GetRoutes()))
