#!/usr/bin/python3
################################################################################
# AGENT PING
#
# Justin Dierking
# phnomcobra@gmail.com
#
# 01/27/2021 Original construction
################################################################################

import argparse

from stembot.adapter.agent import Console

parser = argparse.ArgumentParser(description='agent ping')

parser.add_argument('-a', '--agtuuid', dest='dstuuid', action='store')

kwargs = vars(parser.parse_args())

print(str(Console(kwargs['dstuuid']).ping_peer()))
