services:
  c1:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c1/:/log
    environment:
      - AGT_UUID=c1
      - AGT_PORT=8080
      - AGT_HOST=0.0.0.0
      - AGT_SECRET=password
      - AGT_LOG_PATH=/log
      - AGT_CLIENT_CONTROL_URL=http://127.0.0.1:8080/control
    command:
      - bash
      - -c
      - |
        pip install -q /dist/*.whl
        agt-configure -e
        agt-configure -v
        agt-control discover http://c2:8080/mpi -d 5 &
        agt-server

  c2:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c2/:/log
    command:
      - bash
      - -c
      - |
        pip install -q /dist/*.whl
        agt-configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c2 --log-path /log
        agt-configure -cl
        agt-control discover http://c1:8080/mpi -d 5 &
        agt-control discover http://c3:8080/mpi -d 5 &
        agt-server
  c3:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c3/:/log
    command:
      - bash
      - -c
      - |
        pip install -q /dist/*.whl
        agt-configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c3 --log-path /log
        agt-configure -cl
        agt-control discover http://c2:8080/mpi -d 5 &
        agt-server
  c4:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c4/:/log
    command:
      - bash
      - -c
      - |
        pip install -q /dist/*.whl
        agt-configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c4 --log-path /log
        agt-configure -cl
        agt-control discover http://c2:8080/mpi -p -d 5 &
        agt-control discover http://c5:8080/mpi -d 5 &
        agt-server
  c5:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c5/:/log
    command:
      - bash
      - -c
      - |
        pip install -q /dist/*.whl
        agt-configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c5 --log-path /log
        agt-configure -cl
        agt-control discover http://c4:8080/mpi -d 5 &
        agt-server
