services:
  c1:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c1/:/log
    environment:
      - AGT_UUID=c1
      - AGT_PORT=8080
      - AGT_HOST=0.0.0.0
      - AGT_SECRET=password
      - AGT_LOG_PATH=/log
      - AGT_CLIENT_CONTROL_URL=http://127.0.0.1:8080/control
      - AGT_WORKERS=2
    command:
      - bash
      - -c
      - |
        set -e
        pip install -q /dist/*.whl
        agt-configure --load-env
        agt-configure --view
        agt-control discover http://c2:8080/mpi --delay 10 &
        agt-server

  c2:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c2/:/log
    command:
      - bash
      - -c
      - |
        set -e
        pip install -q /dist/*.whl
        agt-configure --agtuuid c2 --port 8080 --host 0.0.0.0 --secret password --log-path /log --workers 2
        agt-configure --client-local
        agt-control discover http://c1:8080/mpi --delay 10 &
        agt-control discover http://c3:8080/mpi --delay 10 &
        agt-server
  c3:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c3/:/log
    command:
      - bash
      - -c
      - |
        set -e
        pip install -q /dist/*.whl
        agt-configure --agtuuid c3 --port 8080 --host 0.0.0.0 --secret password --log-path /log --workers 2
        agt-configure --client-local
        agt-control discover http://c2:8080/mpi --delay 10 &
        agt-server
  c4:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c4/:/log
    command:
      - bash
      - -c
      - |
        set -e
        pip install -q /dist/*.whl
        agt-configure --agtuuid c4 --port 8080 --host 0.0.0.0 --secret password --log-path /log --workers 2
        agt-configure --client-local
        agt-control discover http://c3:8080/mpi --polling --delay 10 &
        agt-control discover http://c5:8080/mpi --delay 10 &
        agt-server
  c5:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c5/:/log
    command:
      - bash
      - -c
      - |
        set -e
        pip install -q /dist/*.whl
        agt-configure --agtuuid c5 --port 8080 --host 0.0.0.0 --secret password --log-path /log --workers 2
        agt-configure --client-local
        agt-control discover http://c4:8080/mpi --delay 10 &
        agt-server
