services:
  c1:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - .:/staging
    command:
      - bash
      - -c
      - |
        cp -r /staging /app
        cd /app
        rm -f *.sqlite*
        python3 config --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c1
        python3 server &
        SERVER_PID=$!
        sleep 2

        python3 agnet set http://c2:8080/mpi

        wait $SERVER_PID

  c2:
    build: .
    expose:
      - 8080
    volumes:
      - .:/staging
    command:
      - bash
      - -c
      - |
        cp -r /staging /app
        cd /app
        rm -f *.sqlite*
        python3 config --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c2
        python3 server &
        SERVER_PID=$!
        sleep 2

        python3 agnet set http://c1:8080/mpi
        python3 agnet set http://c3:8080/mpi

        wait $SERVER_PID

  c3:
    build: .
    expose:
      - 8080
    volumes:
      - .:/staging
    command:
      - bash
      - -c
      - |
        cp -r /staging /app
        cd /app
        rm -f *.sqlite*
        python3 config --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c3
        python3 server &
        SERVER_PID=$!
        sleep 2

        python3 agnet set http://c2:8080/mpi

        wait $SERVER_PID