services:
  c1:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c1/:/log
    command:
      - bash
      - -c
      - |
        pip install /dist/*.whl
        agt.configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c1 --log-path /log
        agt.configure -cl
        agt.server &
        SERVER_PID=$!
        sleep 4

        agt.control set http://c2:8080/mpi

        wait $SERVER_PID

  c2:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c2/:/log
    command:
      - bash
      - -c
      - |
        pip install /dist/*.whl
        agt.configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c2 --log-path /log
        agt.configure -cl
        agt.server &
        SERVER_PID=$!
        sleep 4

        agt.control set http://c1:8080/mpi
        agt.control set http://c3:8080/mpi

        wait $SERVER_PID

  c3:
    build: .
    expose:
      - 8080
    volumes:
      - ./dist:/dist
      - ./log/c3/:/log
    command:
      - bash
      - -c
      - |
        pip install /dist/*.whl
        agt.configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c3 --log-path /log
        agt.configure -cl
        agt.server &
        SERVER_PID=$!
        sleep 4

        agt.control set http://c2:8080/mpi

        wait $SERVER_PID
  c4:
    build: .
    volumes:
      - ./dist:/dist
      - ./log/c4/:/log
    command:
      - bash
      - -c
      - |
        pip install /dist/*.whl
        agt.configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c4 --log-path /log
        agt.configure -cl
        agt.server &
        SERVER_PID=$!
        sleep 4

        agt.control set http://c2:8080/mpi -p
        agt.control set http://c5:8080/mpi

        wait $SERVER_PID

  c5:
    build: .
    volumes:
      - ./dist:/dist
      - ./log/c5/:/log
    command:
      - bash
      - -c
      - |
        pip install /dist/*.whl
        agt.configure --port 8080 --host 0.0.0.0 --secret-text password --agtuuid c5 --log-path /log
        agt.configure -cl
        agt.server &
        SERVER_PID=$!
        sleep 4

        agt.control set http://c4:8080/mpi

        wait $SERVER_PID