#!/usr/bin/python3
################################################################################
# SERVER
#
# Justin Dierking
# justin.l.dierking.civ@mail.mil
# (614) 692 2050
#
# 01/28/2021 Original construction
################################################################################

from stembot.main import start                                                     
                                                                                
start()
