#!/usr/bin/python3
################################################################################
# SERVER
#
# Justin Dierking
# justin.l.dierking.civ@mail.mil
# (614) 692 2050
#
# 01/28/2021 Original construction
################################################################################

from PySimpleGUIQt import SystemTray
from stembot.main import start                                                     
from threading import Thread

if __name__ == '__main__':
    Thread(target=start).start()
    tray = SystemTray()
