#!/usr/bin/python
################################################################################
# AGENT PUT FILE
#
# Justin Dierking
# phnomcobra@gmail.com
#
# 08/28/2019 Original construction
################################################################################

import argparse

from time import time

from stembot.agentint import Console

parser = argparse.ArgumentParser(description = 'agent put file')

parser.add_argument('-s', '--source', dest = 'source', action = 'store')
parser.add_argument('-d', '--destination', dest = 'destination', action = 'store', default = None)
parser.add_argument('-a', '--agtuuid', dest = 'dstuuid', action = 'store')

kwargs = vars(parser.parse_args())

cli_r = Console(kwargs['dstuuid'])
cli_l = Console()

md5_local_digest = cli_l.system('md5sum ' + kwargs['source']).split(" ")[0]
print md5_local_digest

input_f = cli_l.file(kwargs['source'], 'rb')
output_f = cli_r.file(kwargs['destination'], 'wb')

chunk = b''
bytes_transferred = 0
ti = time()
while True:
    di = time()
    chunk = input_f.read(65535 * 8)

    if len(chunk) == 0:
        break
    
    bytes_transferred += len(chunk)
    output_f.write(chunk)

    print 'Transferred {0} KB, {1} KB/sec...'.format(
        bytes_transferred / 1024, 
        round(bytes_transferred / (time() - ti) / 1024)
    )    
    
output_f.close()
input_f.close()

md5_remote_digest = cli_r.system('md5sum ' + kwargs['destination']).split(" ")[0]
print md5_remote_digest

assert md5_remote_digest == md5_local_digest
